[build]
builders = ['python']

[variables]
NIXPACKS_PYTHON_VERSION = '3.11'
PIP_CACHE_DIR = '/tmp/pip-cache'
PIP_NO_CACHE_DIR = '0'
# Optimize for ML dependencies
PIP_DEFAULT_TIMEOUT = '300'
PIP_DISABLE_PIP_VERSION_CHECK = '1'

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install --upgrade pip setuptools wheel',
  # Install lighter packages first
  'pip install --no-cache-dir Flask Flask-CORS Flask-SQLAlchemy python-dotenv groq requests PyPDF2 azure-storage-blob werkzeug sqlalchemy uuid',
  # Install heavy ML packages separately with optimizations
  'pip install --no-cache-dir --find-links https://download.pytorch.org/whl/cpu torch',
  'pip install --no-cache-dir sentence-transformers numpy faiss-cpu pinecone tiktoken scikit-learn transformers'
]

[start]
cmd = 'python app.py'
