[build]
builders = ['python']

[variables]
NIXPACKS_PYTHON_VERSION = '3.11'
PIP_CACHE_DIR = '/tmp/pip-cache'
PIP_NO_CACHE_DIR = '0'

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install --upgrade pip setuptools wheel',
  'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'python app.py'
