# Streamlit Secrets Configuration Template
# 
# For Streamlit Cloud deployment:
# 1. Copy this content to your Streamlit app's secrets management
# 2. Fill in your actual API keys and configuration values
# 3. DO NOT commit this file with real secrets to version control

# AI Service Configuration
GROQ_API_KEY = "your_groq_api_key_here"
GROQ_MODEL = "llama-3.1-70b-versatile"

# Vector Database Configuration (Pinecone)
PINECONE_API_KEY = "your_pinecone_api_key_here"
PINECONE_ENVIRONMENT = "us-east-1"
PINECONE_INDEX_NAME = "edify-chatbot"

# Azure Storage Configuration (Optional)
AZURE_STORAGE_CONNECTION_STRING = "your_azure_connection_string_here"
AZURE_STORAGE_ACCOUNT_NAME = "your_storage_account_name"
AZURE_STORAGE_CONTAINER_NAME = "edifydocumentcontainer"
AZURE_BLOB_FOLDER_PATH = "edipedia/2025-2026/"

# Edify API Configuration (Optional)
EDIFY_API_BASE_URL = "https://api.edifyschool.in/v1"
EDIFY_API_KEY = "no_auth_required"
EDIFY_API_ENDPOINT = "/edi-pedia/sop-all"

# App Configuration
app_url = "https://your-app-name.streamlit.app"
