app = "ai-chatbot-backend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  FLASK_ENV = "production"
  PORT = "5000"
  HOST = "0.0.0.0"
  LOG_LEVEL = "INFO"
  VECTOR_DB_TYPE = "edify_api"

# Secrets (add via CLI): fly secrets set GROQ_API_KEY=xxx EDIFY_API_KEY=xxx
