version: 2
services:
  - type: web
    name: ai-chatbot-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app_original.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
